version: '3.6'

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - integrador_backend

  gateway:
    container_name: gateway
    image: diegogmrn/gateway:latest
    ports:
      - "3000:3000"
      - "4000:4000"
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - rabbitmq
    networks:
      - integrador_backend

  users:
    container_name: users
    image: diegogmrn/users-microservice:latest
    ports:
      - "8081:8081"
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - rabbitmq
    networks:
      - integrador_backend
  
  payments:
    container_name: users
    image: diegogmrn/payments-microservice:latest
    ports:
      - "8083:8083"
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - rabbitmq
    networks:
      - integrador_backend

  products:
    container_name: products
    image: diegogmrn/products-microservice:latest
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/products?sslmode=disable
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - rabbitmq
    networks:
      - integrador_backend
    volumes:
      - ./.env:/.env

  stock:
    container_name: stock
    image: diegogmrn/stock-microservice:latest
    ports:
      - "8082:8082"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/products?sslmode=disable
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - rabbitmq
    networks:
      - integrador_backend
    volumes:
      - ./.env:/.env

  images:
    container_name: images
    image: diegogmrn/images-microservice:latest
    ports:
      - "8181:8181"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/products?sslmode=disable
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - rabbitmq
    networks:
      - integrador_backend
    volumes:
      - ./.env:/.env
      - ../images:/images  



networks:
  integrador_backend:
    driver: bridge